---
name: Feature request
description: Propose a new capability for the M5Tab5 firmware
labels: [enhancement]
title: "feat: "
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user outcome or workflow gap are we solving?
    validations:
      required: true
  - type: textarea
    id: constraints
    attributes:
      label: Constraints (HW/IDF/Heap)
      description: List hardware quirks, ESP-IDF limits, or memory budgets we must respect.
    validations:
      required: true
  - type: textarea
    id: tests
    attributes:
      label: Acceptance tests
      description: Define objective checks or telemetry we can use to verify success.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / wireframes
      description: Attach mockups, UI references, or layout sketches that guide implementation.
    validations:
      required: false
