name: Build Firmware

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  esp-idf-build:
    name: Build ESP-IDF project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Enforce NG I2C usage
        run: |
          set -euo pipefail
          if git grep -n -- "driver/i2c.h" -- '*.c' '*.h' '*.cpp' '*.hpp' '*.cc'; then
            echo "Legacy I2C include found"
            exit 1
          fi
          if git grep -nE -- "i2c_driver_install|i2c_param_config|i2c_driver_delete|i2c_cmd_link_create|i2c_master_cmd_begin" -- '*.c' '*.h' '*.cpp' '*.hpp' '*.cc'; then
            echo "Legacy I2C API found"
            exit 1
          fi
      - name: Build firmware
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: release-v5.4
          target: esp32p4
          command: python3 fetch_repos.py && idf.py build
      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.sha }}
          path: |
            build/*.bin
            build/*.elf
            build/*.map
            build/flasher_args.json
            build/bootloader/bootloader.bin
            build/partition_table/partition-table.bin
          if-no-files-found: error
