name: IDF Preflight

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 3 * * 1"  # weekly, optional

permissions:
  contents: read

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (no LFS)
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - name: Set up Python (if your installer needs it)
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      # Use your repo's installer (as you asked)
      - name: Run repo install script (ESP-IDF)
        env:
          IDF_VERSION: v5.4.2   # keep in sync with your main build
        run: |
          bash tools/install_idf.sh

      - name: Verify toolchain works
        shell: bash
        run: |
          # Common export paths used by installers; adapt if your script installs elsewhere
          if [ -f "$HOME/esp-idf/export.sh" ]; then
            . "$HOME/esp-idf/export.sh"
          elif [ -f "$HOME/.espressif/esp-idf/export.sh" ]; then
            . "$HOME/.espressif/esp-idf/export.sh"
          fi
          idf.py --version
