name: IDF Build (ESP32-P4)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: false

      - name: Build with ESP-IDF 5.4.2 for ESP32-P4
        uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.4.2
          target: esp32p4
          command: |
            . /opt/esp/idf/export.sh
            cd platforms/tab5
            idf.py set-target esp32p4
            idf.py build
