---
name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive
      - name: Guard against Git LFS usage
        run: |
          if git grep -n "filter=lfs" -- .gitattributes; then
            echo "Refusing to proceed: LFS filters detected in .gitattributes"
            exit 1
          fi
      - uses: frenck/action-yamllint@v1
        with:
          config_file: .yamllint.yml

  superlinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive
      - uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_C: true
          VALIDATE_CPP: true
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
