name: Lint Check

on:
  pull_request:
    paths:
      - '**.c'
      - '**.C'
      - '**.cc'
      - '**.cpp'
      - '**.cxx'
      - '**.c++'
      - '**.h'
      - '**.H'
      - '**.hh'
      - '**.hpp'
      - '**.hxx'
      - '**.h++'
  push:
    branches:
      - main
    paths:
      - '**.c'
      - '**.C'
      - '**.cc'
      - '**.cpp'
      - '**.cxx'
      - '**.c++'
      - '**.h'
      - '**.H'
      - '**.hh'
      - '**.hpp'
      - '**.hxx'
      - '**.h++'
  workflow_dispatch:

jobs:
  clang-format:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: false
          submodules: recursive

      - name: Setup C++ tooling
        uses: aminya/setup-cpp@v1
        with:
          clangformat: 13

      - name: Verify formatting
        shell: bash
        run: |
          files=$(git ls-files '*.c' '*.C' '*.cc' '*.cpp' '*.cxx' '*.c++' '*.h' '*.H' '*.hh' '*.hpp' '*.hxx' '*.h++')
          if [[ -z "$files" ]]; then
            echo 'No tracked C/C++ files to check.'
            exit 0
          fi
          clang-format --dry-run --Werror $files
